CREATE TABLE Category(
   category_id INTEGER GENERATED BY DEFAULT AS IDENTITY,
   name VARCHAR(50)  NOT NULL,
   is_alcoholised BOOLEAN NOT NULL,
   image VARCHAR(100) ,
   description VARCHAR(50) ,
   PRIMARY KEY(category_id)
);

CREATE TABLE Address(
   address_id INTEGER GENERATED BY DEFAULT AS IDENTITY,
   city VARCHAR(50)  NOT NULL,
   zipcode VARCHAR(50)  NOT NULL,
   street VARCHAR(50)  NOT NULL,
   complement VARCHAR(50) ,
   country VARCHAR(50)  NOT NULL,
   PRIMARY KEY(address_id)
);

CREATE TABLE Users(
   user_id INTEGER GENERATED BY DEFAULT AS IDENTITY,
   email VARCHAR(320)  NOT NULL,
   last_name VARCHAR(50)  NOT NULL,
   first_name VARCHAR(50)  NOT NULL,
   phone VARCHAR(20) ,
   password VARCHAR(255)  NOT NULL,
   address_id INTEGER NOT NULL,
   PRIMARY KEY(user_id),
   UNIQUE(email),
   FOREIGN KEY(address_id) REFERENCES address(address_id)
);

CREATE TABLE Token (
    token_id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    user_id integer NOT NULL,
    token text NOT NULL,
    created_at timestamp without time zone NOT NULL DEFAULT now(),
    FOREIGN KEY(user_id) REFERENCES Users(user_id),
    PRIMARY KEY(token_id)
);

CREATE TABLE Product(
   product_id INTEGER GENERATED BY DEFAULT AS IDENTITY,
   image VARCHAR(100) ,
   price NUMERIC(15,2)   NOT NULL,
   stock INTEGER NOT NULL,
   name VARCHAR(50)  NOT NULL,
   volume INTEGER NOT NULL,
   brand VARCHAR(50)  NOT NULL,
   category_id INTEGER NOT NULL,
   PRIMARY KEY(product_id),
   FOREIGN KEY(category_id) REFERENCES Category(category_id)
);

CREATE TABLE Sale(
   sale_id INTEGER GENERATED BY DEFAULT AS IDENTITY,
   discount INTEGER NOT NULL,
   product_id INTEGER NOT NULL,
   PRIMARY KEY(sale_id),
   UNIQUE(product_id),
   FOREIGN KEY(product_id) REFERENCES Product(product_id)
);

CREATE TABLE Orders(
   order_id INTEGER GENERATED BY DEFAULT AS IDENTITY,
   is_confirmed BOOLEAN NOT NULL,
   order_date DATE,
   delivery_date DATE,
   user_id INTEGER NOT NULL,
   PRIMARY KEY(order_id),
   FOREIGN KEY(user_id) REFERENCES Users(user_id)
);

CREATE TABLE Command_product(
   order_id INTEGER,
   product_id INTEGER,
   quantity INTEGER,
   PRIMARY KEY(order_id, product_id),
   FOREIGN KEY(order_id) REFERENCES Orders(order_id),
   FOREIGN KEY(product_id) REFERENCES Product(product_id)
);
